### ISSUE TITLE
Document migration example from melon_images to top_image

### ISSUE THREAD

**Issue by georgringer** [helhum/typo3-top-image#16]
I am currently struggling with the configuration, maybe it would be cool to document how to migrate from eg. EXT:melon_images to this extension.

using a config like
```yaml
breakpoints:
    phone:
        to: 479
    tablet:
        from: 480
        to: 1023
    desktop:
        from: 1024

pixelDensities: [ 1, 2 ]

croppingConfiguration:                            
    tt_content:        
        image:
            image:
                variants:
                    default:
                        sizes:
                            desktop:
                                breakpoints: desktop
                                width: 300
                                ratio: 1/1
                                
                            tablet:
                                breakpoints: tablet
                                width: 350
                                ratio: 1/1
                                
                            phone:
                                breakpoints: phone
                                width: 390
                                ratio: 1/1

        contentelements_keyvisual:
            image:
                variants:
                    default:
                        sizes:
                            desktop:
                                breakpoints: desktop
                                width: 1240
                                ratio: 2/1

                            tablet:
                                breakpoints: tablet
                                width: 720
                                ratio: 2/1
                                
                            phone:
                                breakpoints: phone
                                width: 440
                                ratio: 2/1
        
    tx_news_domain_model_news:
        _all:
            fal_media:
                variants:
                    default:
                        sizes:
                            desktop:
                                breakpoints: desktop
                                width: 390
                                ratio: 16/9

                            tablet:
                                breakpoints: tablet
                                width: 720
                                ratio: 16/9
                                
                            phone:
                                breakpoints: phone
                                width: 440
                                ratio: 16/9

```
